# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(1, 'trivial'), (2, 'mild'), (3, 'important'), (4, 'emergency')], default=1)),
                ('category', models.IntegerField(choices=[(1, 'regular'), (2, 'family'), (3, 'school'), (4, 'office')], default=1)),
            ],
        ),
    ]
